feat: ✨ add OCO_EMOJI_POSITION_BEFORE_DESCRIPTION
di-sukharev/opencommit pull request #288
Opened 2024-01-04 15:09 UTC by ThomasSanson

Hello @di-sukharev,

I have submitted this pull request wherein I have made several amendments to your opencommit project.

1. I have introduced a new configuration key `OCO_EMOJI_POSITION_BEFORE_DESCRIPTION` that allows users to customise the position of the emoji within the commit message. This provides users with greater flexibility in formatting their commit messages.

2. I have updated the instructions within `generateCommitMessageFromGitDiff.ts` to reflect this new option.

3. I have also updated the `README.md` file to include instructions on how to utilise the `OCO_EMOJI_POSITION_BEFORE_DESCRIPTION` configuration. This configuration allows users to determine where the GitMoji should be placed within the commit message.

4. I have updated the assistant to accommodate the new `OCO_EMOJI_POSITION_BEFORE_DESCRIPTION` configuration. The assistant now generates commit messages based on the emoji position specified by the user.

5. Lastly, I have updated the package version from 2.4.2 to 3.0.4 to reflect these new modifications and improvements.

I would like to emphasise that I have tested these modifications locally and everything appears to be functioning as expected.
The results are visible in the commit.

However, I would like to draw your attention to the fact that the documentation for contributing to the project is somewhat sparse. This could make access to contribution more challenging for new contributors. I believe it would be beneficial to enhance this aspect to facilitate community contribution.

Thank you for your time and consideration. I eagerly await your feedback on my pull request.

Close #219

2024-03-23 09:31 UTC, ThomasSanson commented
@di-sukharev, may I kindly request that you assume responsibility for this pull request ?

Indeed, it appears that each time you approve another pull request, it leads to git conflicts on this one. To prevent such occurrences, it seems prudent for you to manage this task, thereby facilitating a more autonomous and direct resolution of the issue.

2024-06-21 18:38 UTC, ThomasSanson commented
> @di-sukharev, may I kindly request that you assume responsibility for this pull request ?
> 
> Indeed, it appears that each time you approve another pull request, it leads to git conflicts on this one. To prevent such occurrences, it seems prudent for you to manage this task, thereby facilitating a more autonomous and direct resolution of the issue.

2024-06-21 18:56 UTC, di-sukharev commented
Will manage when i have time ;) thank you

2026-08-20 09:28 UTC, di-sukharev requested changes
Настройка позиции GitMoji остаётся возможной feature, но этот PR основан на старой prompt архитектуре, конфликтует и включает generated out. Перенесите идею поверх master, не коммитьте out вручную и добавьте prompt/unit tests для обеих позиций и сочетаний OCO_EMOJI/OCO_DESCRIPTION.

2026-08-25 16:37 UTC, ThomasSanson commented
> Configurable GitMoji placement remains a reasonable feature, but this PR is based on the old prompt architecture, conflicts with `master`, and includes generated `out` files. Please port the idea onto `master`, do not commit generated bundles manually, and add prompt/unit tests for both positions and the `OCO_EMOJI`/`OCO_DESCRIPTION` combinations.

Dear @di-sukharev,

I hope this message finds you well.

Revisiting this issue certainly brought a smile to my face (in the most respectful sense). Indeed, two years on, the codebase has evolved considerably, and I would like to commend and thank you once again for your efforts.

I shall endeavour to free up some time to prepare and submit an update.

Kind regards

2026-08-25 17:52 UTC, di-sukharev commented
Thanks for coming back to this. To save you the rebase work, I took the implementation over and rewrote it against the current master. It landed in [c56ec3c](https://github.com/di-sukharev/opencommit/commit/c56ec3cc8de1f8af66b3f165c18955a959727349) with config/env/help support, documentation, Conventional Commit and commitlint prompt handling, `--fgm` support, and regression coverage for both GitMoji positions and the `OCO_EMOJI`/`OCO_DESCRIPTION` combinations. I also preserved your contribution with a `Co-authored-by` credit. Closing this PR as implemented — thank you for the original contribution!

2026-08-25 17:52 UTC, closed without merging

2026-08-25 18:03 UTC, di-sukharev commented
One more follow-up for completeness: [PR #585](https://github.com/di-sukharev/opencommit/pull/585) adds regression coverage for the commitlint prompt path, omit-scope formatting, localized full-width colon separators, and the no-separator fallback. It has now been merged into master after all checks passed, keeping the implementation easy to maintain across all supported prompt shapes.